@startuml
actor User
participant "Web-Frontend" as WebFrontend
participant Filesystem
participant RabbitMQ
participant "Client-side python script" as ClientSidePythonScripts
participant "CS:GO Client" as GameClient
participant "CS:GO Server" as GameServer
participant "Sourcemod Plugins" as SourcemodPlugins

note over SourcemodPlugins: sm_changeskin,\nsm_gloves,\nsm_sticker\nsm_teleport

User -> WebFrontend: Requests skin screenshot
WebFrontend -> RabbitMQ: Sends message
RabbitMQ <-- ClientSidePythonScripts: Consumes message
ClientSidePythonScripts -> GameClient: Changes skin via console
GameClient <-> GameServer
GameServer <-> SourcemodPlugins: Handles custom console commands
ClientSidePythonScripts -> GameClient: Takes screenshot
ClientSidePythonScripts -> Filesystem: Saves screenshot

WebFrontend <-> User: Periodically updates
WebFrontend -> Filesystem: Reads screenshot
WebFrontend -> User: Sends screenshot
@enduml
